var builder = DistributedApplication.CreateBuilder(args);

// Password auto-generated by Aspire into a parameter resource — never hardcoded. The data
// volume persists across `aspire run`s so local state survives a restart.
var postgres = builder.AddPostgres("postgres")
    .WithDataVolume();

var misedb = postgres.AddDatabase("misedb");

// Phase 2's placeholder JWT-bearer signing key (ADR-004's real StaffIdentity-issued tokens
// land in Phase 3), shared by apiservice (validates) and webfrontend (mints its own
// system-identity token). Not auto-generated like the Postgres password above — set once
// per machine with `dotnet user-secrets set Parameters:jwt-signing-key <value>` from
// src/Mise.AppHost (see README).
var jwtSigningKey = builder.AddParameter("jwt-signing-key", secret: true);

// Mise.MigrationService migrates every module's DbContext, then exits. apiservice waits for
// it to complete before starting — schema-readiness is a precondition of serving traffic,
// not something the API host does for itself on boot.
var migrations = builder.AddProject<Projects.Mise_MigrationService>("migrations")
    .WithReference(misedb)
    .WaitFor(misedb);

var apiService = builder.AddProject<Projects.Mise_ApiService>("apiservice")
    .WithReference(misedb)
    .WaitFor(misedb)
    .WithEnvironment("Authentication__Jwt__SigningKey", jwtSigningKey)
    .WaitForCompletion(migrations)
    .WithHttpHealthCheck("/health");

builder.AddProject<Projects.Mise_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithHttpHealthCheck("/health")
    .WithReference(apiService)
    .WithEnvironment("Authentication__Jwt__SigningKey", jwtSigningKey)
    .WaitFor(apiService);

builder.Build().Run();
