var builder = DistributedApplication.CreateBuilder(args);

// Password auto-generated by Aspire into a parameter resource — never hardcoded. The data
// volume persists across `aspire run`s so local state survives a restart; Mise.MigrationService
// (Phase 2, once the first module has a DbContext to migrate) becomes the thing the API
// waits on instead of the raw database, so schema-readiness is a precondition of serving
// traffic rather than something the API host does for itself on boot.
var postgres = builder.AddPostgres("postgres")
    .WithDataVolume();

var misedb = postgres.AddDatabase("misedb");

var apiService = builder.AddProject<Projects.Mise_ApiService>("apiservice")
    .WithReference(misedb)
    .WaitFor(misedb)
    .WithHttpHealthCheck("/health");

builder.AddProject<Projects.Mise_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithHttpHealthCheck("/health")
    .WithReference(apiService)
    .WaitFor(apiService);

builder.Build().Run();
