<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mise.ServiceDefaults\Mise.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Modules\Mise.Modules.Reservations.Infrastructure\Mise.Modules.Reservations.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Mise.Modules.StaffIdentity.Infrastructure\Mise.Modules.StaffIdentity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Mise.Modules.Tables.Infrastructure\Mise.Modules.Tables.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Mise.Modules.Scheduling.Infrastructure\Mise.Modules.Scheduling.Infrastructure.csproj" />
  </ItemGroup>

</Project>
